import { Metadata } from "next";
import Navbar from "./components/Navbar";
import "./globals.css";
import NavbarLayout from "./components/NavbarLayout";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavbarLayout />
        {children}
      </body>
    </html>
  );
}
